version: '3'

services:
  profile-web:
    command: node bin/server.js
    image: mozilla/fxa-profile-server
    ports:
      - "1111:1111"
  profile-worker:
    command: node bin/worker.js
    image: mozilla/fxa-profile-server
    ports:
      - "1113:1113"
