version: '2.1'

services:
  # fxa-content-server
  fxa-content-web:
    command: node server/bin/fxa-content-server.js
    environment:
      NODE_ENV: "development"
      HOST: "0.0.0.0"
      EXPERIMENTS_ENABLE_POLLING: 'false'
      EXPERIMENTS_GIT_REPO: ""
    image: mozilla/fxa-content-server
    ports:
      - "3030:3030"

  # fxa-auth-server
  auth:
    command: node bin/key_server.js
    environment:
      NODE_ENV: "dev"
      HOST: "0.0.0.0"
    image: mozilla/fxa-auth-server
    depends_on:
      auth-db-mysql:
        condition: service_healthy
    ports:
      - "9000:9000"

  # fxa-oauth-server
  oauth-web:
    command: node bin/server.js
    environment:
      NODE_ENV: "dev"
      HOST: "0.0.0.0"
    image: mozilla/fxa-oauth-server
    ports:
      - "9010:9010"

  # fxa-auth-db-mysql
  auth-db-mysql:
    command: node bin/mem.js
    environment:
      HOST: "0.0.0.0"
    image: mozilla/fxa-auth-db-mysql
    ports:
      - "8000:8000"
    healthcheck:
      test: curl --fail http://127.0.0.1:8000/ || exit 1
      interval: 2s
      timeout: 5s
      retries: 30

  # fxa-profile-server
  profile-web:
    command: node scripts/run_dev.js
    environment:
      HOST: "0.0.0.0"
      WORKER_HOST: "0.0.0.0"
    image: mozilla/fxa-profile-server
    ports:
      - "1111:1111"
      - "1112:1112"
      - "1113:1113"

  # fxa-customs-server
  customs:
    command: node bin/customs_server.js
    environment:
      IP_ADDRESS: "0.0.0.0"
    image: mozilla/fxa-customs-server
    ports:
      - "7000:7000"

  # mysql 5.6
  mysql:
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: fxa
      MYSQL_USER: root
    image: mysql:5.6
    ports:
      - "3306:3306"

volumes:
  db_data:
